categories = {
    'k06:kenobj-2-reality':     ['k06:kenobj-303-aantal_reality',
                                 'k06:kenobj-301-debat_reality',
                                 'k06:kenobj-302-polls_reality',
                                 'k06:kenobj-2-reality'],
    'k06:kenobj-3-ideal':       ['k06:kenobj-3-ideal'],
    'k06:kenobj-partij':        ['k06:kenobj-cda',
                                 'k06:kenobj-partij',
                                 'k06:kenobj-vvd',
                                 'k06:kenobj-50341-christenunie',
                                 'k06:kenobj-d66',
                                 'k06:kenobj-50342-groenlinks',
                                 'k06:kenobj-50349-groepnawijn',
                                 'k06:kenobj-50348-groepwilderspartijvoordevrijheid',
                                 'k06:kenobj-50343-lpf',
                                 'k06:kenobj-50344-pvda',
                                 'k06:kenobj-50345-sgp',
                                 'k06:kenobj-50346-sp',
                                 'k06:kenobj-nieuwepartijen',
                                 'k06:kenobj-5033-oppositiepartijen',
                                 'k06:kenobj-regeringspartij'],
    'k06:kenobj-501-regering':  ['k06:kenobj-501-regering',
                                 'k06:kenobj-5021-koningshuis'],
    'k06:kenobj-4-actor':       ['k06:kenobj-508-buitenland',
                                 'k06:kenobj-504-maatschappij',
                                 'k06:kenobj-5022-politiekdenhaag',
                                 'k06:kenobj-502616-politiek',
                                 'k06:kenobj-510-rechterlijkemacht',
                                 'k06:kenobj-509-zwaardmacht',
                                 'k06:kenobj-503-overheid'],
    'k06:kenobj-5051-media':    ['k06:kenobj-5051-media'],
    'k06:kenobj-6-richtingen':  ['k06:kenobj-701-leftistissues',
                                 'k06:kenobj-702-rightistissues',
                                 'k06:kenobj-703-valenceissues',
                                 'k06:kenobj-704-immigrantsasylumseekers',
                                 'k06:kenobj-706-infrastructure',
                                 'k06:kenobj-705-christianvalues',
                                 'k06:kenobj-707-environment',
                                 'k06:kenobj-708-administrativereforms',
                                 'k06:kenobj-709-newleftissues',
                                 'k06:kenobj-710-eueurope',
                                 'k06:kenobj-617-campaign',
                                 'k06:kenobj-711-crime',
                                 'k06:kenobj-712-healthcare',
                                 'k06:kenobj-714-education',
                                 'k06:kenobj-715-terror',
                                 'k06:kenobj-713-internationalintervention'],
    'k06:kenobj-5-issues':      ['k06:kenobj-601-D01socialezekerheid',
                                 'k06:kenobj-602-D02economischezaken',
                                 'k06:kenobj-603-DLNV',
                                 'k06:kenobj-604-DDefensie',
                                 'k06:kenobj-605-D03Financien',
                                 'k06:kenobj-606-D04nieuwlinks',
                                 'k06:kenobj-607-D05Buitenlandsezaken',
                                 'k06:kenobj-608-D06Onderwijscultuurenwetenschappen',
                                 'k06:kenobj-609-D14Vreemdelingenzaken',
                                 'k06:kenobj-610-D09justitie',
                                 'k06:kenobj-611-D10VolkshuisvestingRuimtelijkeordeningmilieu',
                                 'k06:kenobj-612-D11bestuurlijkevernieuwing',
                                 'k06:kenobj-613-D13verkeerenvervoer',
                                 'k06:kenobj-614-D17Terrorisme',
                                 'k06:kenobj-615-healthcare',
                                 'k06:kenobj-616-christelijkeethiekennormenenwaarden'],
    'zu:zurichcat':             ['zu:cat-01-welfare',
                                 'zu:cat-02-ecolib',
                                 'zu:cat-03-budget',
                                 'zu:cat-05-europe',
                                 'zu:cat-06-culture',
                                 'zu:cat-07-immigration',
                                 'zu:cat-08-army',
                                 'zu:cat-09-security',
                                 'zu:cat-04-cultlib',
                                 'zu:cat-10-eco',
                                 'zu:cat-11-iref',
                                 'zu:cat-12-infra',
                                 ]
    }


CAT_ISSUE_FIRST =(('rdfs:subClassOf',
                    'ont:memberOfParty'),
                   ('k06:kenobj-6-richtingen',
                    'k06:kenobj-partij',
                    'k06:kenobj-5051-media',
                    'k06:kenobj-4-actor',
                    'k06:kenobj-501-regering',
                    'k06:kenobj-3-ideal',
                    'k06:kenobj-2-reality',
                    ))

CAT_ACTOR_FIRST =(('rdfs:subClassOf',
                    'ont:memberOfParty'),
                   ('k06:kenobj-partij',
                    'k06:kenobj-5051-media',
                    'k06:kenobj-4-actor',
                    'k06:kenobj-501-regering',
                    'k06:kenobj-6-richtingen',
                    'k06:kenobj-3-ideal',
                    'k06:kenobj-2-reality'))

CAT_THEMA_FIRST = (('rdfs:subClassOf',
                    'ont:memberOfParty'),
                   ('k06:kenobj-5-issues',
                    'k06:kenobj-partij',
                    'k06:kenobj-5051-media',
                    'k06:kenobj-4-actor',
                    'k06:kenobj-501-regering',
                    'k06:kenobj-3-ideal',
                    'k06:kenobj-2-reality',
                    'k06:kenobj-6-richtingen'))

CAT_TH_ACTOR_FIRST = (('rdfs:subClassOf',
                       'ont:memberOfParty'),
                      ('k06:kenobj-partij',
                       'k06:kenobj-5051-media',
                       'k06:kenobj-4-actor',
                       'k06:kenobj-501-regering',
                       'k06:kenobj-5-issues',
                       'k06:kenobj-3-ideal',
                       'k06:kenobj-2-reality',
                       'k06:kenobj-6-richtingen'))

CAT_ZURICH = (('zu:incategory',
               'rdfs:subClassOf'),
              ('zu:zurichcat',
               ))

def allcats(system):
    result = set()
    for root in system[1]:
        result |= set(categories[root])
    return result
