
BZK_ALIASES = {
    'DUIC': 'DUIC', 'Nos.nl ': 'NOS', 'Dichtbij.nl  ': 'Dichtbij.nl',
    'Nu.nl  31-05-2013 (p.': 'nu.nl - website', 'gelderlander.nl': 'De Gelderlander',
    'Het Parool': 'Het Parool', 'Volkskrant.nl ': 'De Volkskrant', 'Nu.nl': 'nu.nl - website',
    'Binnenlands Bestuur': 'Binnenlandsbestuur.nl', 'Brabants DAgblad': 'Brabants Dagblad',
    'binnenlandsbestuur.nl': 'Binnenlandsbestuur.nl', 'RTLZ.nl': 'RTL nieuws', 'Republic': 'Re.Public',
    'Caribisch, NIEUWS ': 'Caribisch Nederland', 'Rotterdams Dagblad ': 'Algemeen Dagblad',
    'Brandpunt': 'Brandpunt', 'Leeuwarder Courant': 'Leeuwarder Courant',
    'Omroep Flevoland': 'Omroep Flevoland', 'NRC.NEXT': 'NRC Next', 'RTV N-H': 'RTV N-H',
    'Rtvnoordholland.nl ': 'RTV N-H', 'binnenlandsbestuur': 'Binnenlandsbestuur.nl',
    'Ant. D. ': 'Antilliaans Dagblad', 'AD-RD': 'Algemeen Dagblad', 'Buitenhof': 'Buitenhof',
    'NOSNieuws.nl ': 'NOS', 'Dagblad Flevoland  ': 'Dagblad Flevoland',
    'Ref DB ': 'Redormatorisch Dagblad', 'Een vandaag': 'Een vandaag',
    'PZC': 'Provinciale Zeeuwse Courant', 'De Volkskrant': 'De Volkskrant',
    'De Stentor  Dagblad Flevoland ': 'Stentor', 'Algemeen Dagblad': 'Algemeen Dagblad',
    'omroepgelderland.nl': 'Omroep Gelderland', 'RTL Nieuws ': 'RTL nieuws',
    'RTV-rijnmond ': 'RTV Rijnmond', 'Dichtbij.nl': 'Dichtbij.nl', 'Trouw - website': 'Trouw',
    ' Binnenlandsbestuur ': 'Binnenlandsbestuur.nl', 'Cobouw.nl': 'Cobouw', 'Metro NL': 'Metro',
    'Rtlnieuws.nl': 'RTL nieuws', 'AD Rotterdams': 'Algemeen Dagblad',
    'Rtlnieuws.nl  01-06-2013 (p.': 'RTL nieuws', 'Amigoe.com ': 'Amigoe',
    'Noordhollanddagblad.nl': 'Noordhollands Dagblad', 'Almerevandaag ': 'Almerevandaag',
    'Elsevier.nl': 'Elsevier', 'Binnenlandsbestuur.nl': 'Binnenlandsbestuur.nl',
    'AD.nl': 'Algemeen Dagblad', 'Nu.nl ': 'nu.nl - website',
    'Antilliaans Dagblad': 'Antilliaans Dagblad', 'RTL Nieuws': 'RTL nieuws',
    'Het Financieele Dagblad': 'Het Financieele Dagblad', 'Cobouw ': 'Cobouw',
    'BinnenlandsBestuur.nl': 'Binnenlandsbestuur.nl', 'Radar TROS': 'Radar TROS', 'NOS.nl ': 'NOS',
    'Katholieknieuwsblad.nl ': 'Katholiek Nieuwsblad', 'Nos.nl  31-05-2013 (p.': 'NOS',
    'Delimburger.nl ': 'Delimburger.nl', 'RTLnieuws.nl': 'RTL nieuws',
    'Binnelandsbestuur.nl ': 'Binnenlandsbestuur.nl', 'Omroepwest.nl': 'Omroep West',
    '01-06-2013 (p.': 'unknown', ' Binnenlands Bestuur': 'Binnenlandsbestuur.nl',
    'NRC-next': 'NRC Next', 'RTV Noord ': 'RTV Noord', 'EenVandaag ': 'Een vandaag',
    'Caribischnetwerk.ntr.nl': 'NTR Caribisch netwerk', 'webwereld': 'Webwereld',
    'AD Rotterdams Dagblad': 'Algemeen Dagblad', 'VNG': 'VNG', 'De Gelderlander': 'De Gelderlander',
    'Leidsch Dagblad.nl ': 'Leidsch Dagblad', 'Omroep West': 'Omroep West', 'Stentor': 'Stentor',
    'Ad.nl ': 'Algemeen Dagblad', 'Nos.nl  ': 'NOS', 'Omroep Zeeland': 'Omroep Zeeland',
    'Ant. D.': 'Antilliaans Dagblad', 'Daily Herald': 'Daily Herald', 'BN/DeStem': 'BN/DeStem',
    'Trouw.nl': 'Trouw', 'Nrc.nl ': 'NRC', 'Binnenlands Bestuur.nl': 'Binnenlandsbestuur.nl',
    'ND.nl': 'Nederlands Dagblad', 'ANP': 'ANP',
    'Provinciale Zeeuwse Courant ': 'Provinciale Zeeuwse Courant', 'Cobouw.nl  01-06-2013 (p.': 'Cobouw',
    'Telegraaf.nl': 'De Telegraaf', ' NOS.nl': 'NOS', 'NRC Handelsblad': 'NRC',
    'ND': 'Nederlands Dagblad', 'Nos.nl': 'NOS', 'Spits': 'Spits',
    'Dablad van het Noorden': 'Dagblad van het Noorden', 'Destentor.nl ': 'Stentor',
    'RTLnieuws': 'RTL nieuws', 'nrc next': 'NRC Next', 'Binnenlandbestuur.nl': 'Binnenlandsbestuur.nl',
    'RTV Utrecht': 'RTV Utrecht', 'unknown': 'unknown', 'Cobouw.nl  ': 'Cobouw', 'Amigoe': 'Amigoe',
    'Binnenlands bestuur': 'Binnenlandsbestuur.nl', 'Nederlands Dagblad': 'Nederlands Dagblad',
    'Haarlems Dagblad': 'Haarlems Dagblad', 'Telegraaf.nl ': 'De Telegraaf', 'NRCnext': 'NRC Next',
    'AD ': 'Algemeen Dagblad', 'Nu.nl  01-06-2013 (p.': 'nu.nl - website', 'Nieuws.nl': 'Nieuws.nl',
    'Omroepflevoland,nl ': 'Omroep Flevoland', 'Novum ': 'Novum', 'Webwereld.nl ': 'Webwereld',
    'Versgeperst': 'Versgeperst', 'Refdag.nl ': 'Redormatorisch Dagblad',
    'AD/Rotterdams Dagblad ': 'Algemeen Dagblad', 'Re.Public': 'Re.Public', 'NOS.nl': 'NOS',
    'Ant. D': 'Antilliaans Dagblad', 'Haarlems Dagblad ': 'Haarlems Dagblad',
    'Parool.nl': 'Het Parool', 'Next': 'NRC Next', 'AD/Groene Hart ': 'Algemeen Dagblad',
    'Cobouw.nl ': 'Cobouw', 'Ant. Dagblad': 'Antilliaans Dagblad', 'Cobouw': 'Cobouw',
    'AD/Amersfoortse Courant': 'Algemeen Dagblad', 'Binnenlandsbestuur ': 'Binnenlandsbestuur.nl',
    'Omroepflevoland.nl ': 'Omroep Flevoland', 'Parool': 'Het Parool', 'Rtvdrenthe': 'RTV Drenthe',
    'Radio 1': 'Radio 1', 'AT5': 'AT5', 'Caribisch Nederland': 'Caribisch Nederland',
    'Volkskrant.nl': 'De Volkskrant', 'nu.nl - website': 'nu.nl - website', 'NOS TT ': 'NOS',
    'Daily herald': 'Daily Herald', 'rtv drenthe ': 'RTV Drenthe', 'Rtvnoord.nl': 'RTV Noord',
    'MEdiawatch': 'Mediawatch', 'Ant. D. 01-06-2013 (p.': 'Antilliaans Dagblad',
    'Amigoe.com  01-06-2013 (p.': 'Amigoe', 'BINNENLANDS BESTUUR': 'Binnenlandsbestuur.nl',
    'NTR Caribisch netwerk': 'NTR Caribisch netwerk', 'Rtlnieuws.nl ': 'RTL nieuws',
    'Friesch Dagblad': 'Friesch Dagblad', 'EenVandaag': 'Een vandaag', 'Trouw': 'Trouw',
    'de Volkskrant': 'De Volkskrant', 'Computable.nl ': 'Computable.nl',
    'Dagblad Tubantia/Twentsche Courant': 'Dagblad Tubantia/Twentsche Courant',
    'Leidsch Dagblad': 'Leidsch Dagblad', 'De Gooi- en Eemlander': 'De Gooi- en Eemlander',
    'Dagblad van het Noorden': 'Dagblad van het Noorden', 'bndestem.nl': 'BN/DeStem',
    'rtv Noord': 'RTV Noord', 'nu.nl': 'nu.nl - website', 'Brabants Dagblad': 'Brabants Dagblad',
    'nrc': 'NRC', 'Hart van Nederland': 'Hart van Nederland', 'Rd.nl  ': 'Redormatorisch Dagblad',
    'Noordhollands Dagblad ': 'Noordhollands Dagblad', 'AD/Rotterdams Dagblad': 'Algemeen Dagblad',
    'NRC.nl': 'NRC', 'Metro': 'Metro', 'Thepostonline.nl ': 'Thepostonline.nl',
    'Reformatorisch Dagblad': 'Redormatorisch Dagblad', 'Eenvandaag.nl ': 'Een vandaag',
    'De Stentor / Sallands Dagblad': 'Stentor', 'Elsevier': 'Elsevier',
    'Binnenlandsbestuur.nl ': 'Binnenlandsbestuur.nl', 'VK.nl ': 'De Volkskrant', 'BNR.nl': 'BNR.nl',
    'hpdetijd.nl ': 'hpdetijd.nl', 'De Telegraaf': 'De Telegraaf', 'NRC Next': 'NRC Next',
    'NRC': 'NRC', 'Het Financieele Dagblad - website': 'Het Financieele Dagblad',
    'Dagblad Flevoland': 'Dagblad Flevoland', 'Sargasso.nl': 'Sargasso.nl',
    'Brabantsdagblad.nl ': 'Brabants Dagblad', 'Haagsche Courant': 'Haagsche Courant',
    'AD/Utrechts Dagblad': 'Algemeen Dagblad'
}
