BZK_ALIASES = {
  '1Vandaag': ('Actualiteiten', '1Vandaag'),
  '5 jaar later': ('Actualiteiten', '5 jaar later'),
  'Actualiteiten': ('Actualiteiten', 'Actualiteiten'),
  'Altijd Wat': ('Actualiteiten', 'Altijd Wat'),
  'Andere Tijden': ('Actualiteiten', 'Andere Tijden'),
  'Argos-TV Medalogica': ('Actualiteiten', 'Medialogica'),
  'Beau': ('Actualiteiten', 'RTL4'),
  'Blauw Bloed': ('Actualiteiten', 'Blauw Bloed'),
  'BNN': ('Actualiteiten', 'BNN'),
  'Brandpunt': ('Actualiteiten', 'Brandpunt'),
  'Brandpuntplus': ('Actualiteiten', 'Brandpunt'),
  'Buitenhof': ('Actualiteiten', 'Buitenhof'),
  'College Tour': ('Actualiteiten', 'College Tour'),
  'De Kwis': ('Actualiteiten', 'De Kwis'),
  'De Monitor': ('Actualiteiten', 'De Monitor'),
  'De week van Powned': ('Actualiteiten', 'Powned'),
  'De wereld draait door': ('Actualiteiten', 'DWDD'),
  'Dit is de dag': ('Actualiteiten', 'Dit is de dag'),
  'Dit is de Dag': ('Actualiteiten', 'Dit is de dag'),
  'Dit was het Nieuws': ('Actualiteiten', 'Dit was het Nieuws'),
  'DWDD': ('Actualiteiten', 'DWDD'),
  'Editie NL': ('Actualiteiten', 'Editie NL'),
  'Editie.nl': ('Actualiteiten', 'Editie NL'),
  'Een Vandaag': ('Actualiteiten', '1Vandaag'),
  'Een vandaag': ('Actualiteiten', '1Vandaag'),
  'Eén Vandaag': ('Actualiteiten', '1Vandaag'),
  'EenVandaag': ('Actualiteiten', '1Vandaag'),
  'EénVandaag': ('Actualiteiten', '1Vandaag'),
  'EenVandaag tv': ('Actualiteiten', '1Vandaag'),
  'EenVandaag vrijdag 18 april': ('Actualiteiten', '1Vandaag'),
  'EenVandaag.nl': ('Actualiteiten', '1Vandaag'),
  'Eenvandaag.nl': ('Actualiteiten', '1Vandaag'),
  'EO': ('Actualiteiten', 'EO'),
  'Eo.nl  ': ('Actualiteiten', 'EO'),
  'Goedemorgen Nederland': ('Actualiteiten', 'Goedemorgen Nederland'),
  'Haagse Lobby': ('Actualiteiten', 'Haagse Lobby'),
  'Hallo Nederland': ('Actualiteiten', 'Hallo Nederland'),
  'Hart van Nederland': ('Actualiteiten', 'Hart van Nederland'),
  'jinek': ('Actualiteiten', 'Jinek'),
  'Jinek': ('Actualiteiten', 'Jinek'),
  'Kassa': ('Actualiteiten', 'Kassa'),
  'Kassa.nl': ('Actualiteiten', 'Kassa'),
  'Knelpunt MAX': ('Actualiteiten', 'Knelpunt MAX'),
  'Knevel en van den Brink': ('Actualiteiten', 'Knevel en van den Brink'),
  'Laat op Een': ('Actualiteiten', 'Laat op Een'),
  'M NPO 1': ('Actualiteiten', 'M.'),
  'M.': ('Actualiteiten', 'M.'),
  'MaxVandaag.nl': ('Actualiteiten', 'Max'),
  'Meldpunt (Max)': ('Actualiteiten', 'Max'),
  'Monitor': ('Actualiteiten', 'De Monitor'),
  'N1': ('Actualiteiten', 'Actualiteiten'),
  'N2': ('Actualiteiten', 'Actualiteiten'),
  'Nieuwsuur': ('Actualiteiten', 'Nieuwsuur'),
  'Nieuwsuur.nl': ('Actualiteiten', 'Nieuwsuur'),
  'nieuwsuur.nl': ('Actualiteiten', 'Nieuwsuur'),
  'NPO 1 - Op1': ('Actualiteiten', 'Op1'),
  'NPO 2': ('Actualiteiten', 'Actualiteiten'),
  'NPO 3': ('Actualiteiten', 'NPO op 3'),
  'NPO op 3': ('Actualiteiten', 'NPO op 3'),
  'NPO2': ('Actualiteiten', 'Actualiteiten'),
  'NPO2 Hallo Nederland': ('Actualiteiten', 'NPO2 Hallo Nederland'),
  'Omroep Max': ('Actualiteiten', 'Max'),
  'Oog in oog': ('Actualiteiten', 'Oog in oog'),
  'Op1': ('Actualiteiten', 'Op1'),
  'Op1 NPO 1': ('Actualiteiten', 'Op1'),
  'Opgelicht': ('Actualiteiten', 'Opgelicht'),
  'Ovpro.nl ': ('Actualiteiten', 'VPRO'),
  'Pauw': ('Actualiteiten', 'Pauw'),
  'Pauw & Witteman': ('Actualiteiten', 'Pauw'),
  'Pauw en Jinek': ('Actualiteiten', 'Pauw en Jinek'),
  'Pauw en Witteman': ('Actualiteiten', 'Pauw'),
  'Pow Nieuws': ('Actualiteiten', 'Powned'),
  'Pow-ned': ('Actualiteiten', 'Powned'),
  'Powned.tv': ('Actualiteiten', 'Powned'),
  'Pownews': ('Actualiteiten', 'Powned'),
  'Radar': ('Actualiteiten', 'Radar'),
  'Radar.nl': ('Actualiteiten', 'Radar'),
  'Radar TROS': ('Actualiteiten', 'Radar'),
  'RTL 7 Businessclass': ('Actualiteiten', 'RTL7'),
  'RTL Late Night': ('Actualiteiten', 'RTL4'),
  'RTL Z nieuws': ('Actualiteiten', 'RTLZ'),
  'RTLZ': ('Actualiteiten', 'RTLZ'),
  'RTLZ today': ('Actualiteiten', 'RTLZ'),
  'rtlz.nl': ('Actualiteiten', 'RTLZ'),
  'SBS 6': ('Actualiteiten', 'SBS6'),
  'Studio Powned': ('Actualiteiten', 'Powned'),
  'Talkshow M': ('Actualiteiten', 'Talkshow M'),
  'NPO 1 | Talkshow M': ('Actualiteiten', 'Talkshow M'),
  'Tijd voor Max': ('Actualiteiten', 'Tijd voor Max'),
  'Tros Radar': ('Actualiteiten', 'Radar'),
  'TROS radar.nl': ('Actualiteiten', 'Radar'),
  'Vandaag de dag': ('Actualiteiten', 'Vandaag de dag'),
  'Villa VPRO': ('Actualiteiten', 'VPRO'),
  'Welingelichte Kringen': ('Actualiteiten', 'Welingelichte Kringen'),
  'WNL': ('Actualiteiten', 'WNL'),
  'WNL Haagse Lobby': ('Actualiteiten', 'WNL'),
  'WNL op Zaterdag': ('Actualiteiten', 'WNL'),
  'WNL op Zondag': ('Actualiteiten', 'WNL'),
  'WNL.nl': ('Actualiteiten', 'WNL'),
  'WNL.tv': ('Actualiteiten', 'WNL'),
  'Zembla': ('Actualiteiten', 'Zembla'),
  'Zembla.nl': ('Actualiteiten', 'Zembla'),
  'zembla.nl': ('Actualiteiten', 'Zembla'),
  'zemla': ('Actualiteiten', 'Zembla'),
  'Zomergasten': ('Actualiteiten', 'Zomergasten'),
  'Zondag met Lubach': ('Actualiteiten', 'Zondag met Lubach'),
  'Pointer KRO-NCRV': ('Actualiteiten', 'Pointer'),
  'AD.nl': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'AD ': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'ad.nl': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'Ad.nl': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'AD/Algemeen Dagblad': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'AD/Algemeen Dagblad': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'AD/Algemeen Dagblad 12 juli 2019 vrijdag': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'AD/Algemeen Dagblad.nl': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  'Algemeen Dagblad': ('Algemeen Dagblad', 'Algemeen Dagblad'),
  '(c) ANP': ('ANP', 'ANP'),
  '(c) ANP 2014': ('ANP', 'ANP'),
  'Algemeen Nederlands Persbureau ANP': ('ANP', 'ANP'),
  'ANP': ('ANP', 'ANP'),
  'anp': ('ANP', 'ANP'),
  'ANP ': ('ANP', 'ANP'),
  'ANP 1o oktober 2015': ('ANP', 'ANP'),
  'ANP 2014': ('ANP', 'ANP'),
  'ANP 3 2020': ('ANP', 'ANP'),
  'ANP Binnenland': ('ANP', 'ANP'),
  'ANP Economie': ('ANP', 'ANP'),
  'ANP vrijdag': ('ANP', 'ANP'),
  'ANP:': ('ANP', 'ANP'),
  'ANP/ Annick van der Peet': ('ANP', 'ANP'),
  'Nieuws.nl/novum': ('ANP', 'ANP'),
  'Novum': ('ANP', 'ANP'),
  'Novum ': ('ANP', 'ANP'),
  'binnenlandsbestuur': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'BB': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binbest': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'binbest': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnelandsbestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands bestuur': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands Bestuur': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'BINNENLANDS BESTUUR': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands bestuur ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands Bestuur Magazine': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands Bestuur nieuwssite': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands Bestuur nieuwssite ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'BinnenlandsBestuur': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbestuur': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'binnenlandsbestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbestuur.nl ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbestuur.nl  ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbestuur.nl   11-10-2013 (p.': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbesuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsbesuur.nl ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandsebstuur.nl ': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlandbestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'Binnenlands Bestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'BinnenlandsBestuur.nl': ('Binnenlands bestuur', 'Binnenlands bestuur'),
  'BNR': ('BNR', 'BNR'),
  'BNR B.L.T.': ('BNR', 'BNR'),
  'BNR Ochtendspits': ('BNR', 'BNR'),
  'BNR Radio': ('BNR', 'BNR'),
  'BNR.nl': ('BNR', 'BNR'),
  'BNR.nl vrijdag': ('BNR', 'BNR'),
  ' Caribisch Netwerk': ('Buitenland', 'Caribisch Netwerk'),
  'ABC online media': ('Buitenland', 'ABC online'),
  'Amigoe': ('Buitenland', 'Amigoe'),
  'amigoe': ('Buitenland', 'Amigoe'),
  'Amigoe ': ('Buitenland', 'Amigoe'),
  'Amigoe.com  01-06-2013 (p.': ('Buitenland', 'Amigoe'),
  'Amigoe.com ': ('Buitenland', 'Amigoe'),
  'Amigoe.com  ': ('Buitenland', 'Amigoe'),
  'Ant. Dagblad': ('Buitenland', 'Antiliaans Dagblad'),
  'ANT. Dagblad': ('Buitenland', 'Antiliaans Dagblad'),
  'Ant. D.': ('Buitenland', 'Antiliaans Dagblad'),
  'Ant. D': ('Buitenland', 'Antiliaans Dagblad'),
  'Ant. D. 01-06-2013 (p.': ('Buitenland', 'Antiliaans Dagblad'),
  'Ant. D.': ('Buitenland', 'Antiliaans Dagblad'),
  'Antiliaans Dagblad': ('Buitenland', 'Antiliaans Dagblad'),
  'Antillaans Dagblad': ('Buitenland', 'Antiliaans Dagblad'),
  'Antilliaans Dagblad': ('Buitenland', 'Antiliaans Dagblad'),
  'antilliaansdagblad.com': ('Buitenland', 'Antiliaans Dagblad'),
  'aruba.nu': ('Buitenland', 'Arubanieuws.nu'),
  'Aruba.nu': ('Buitenland', 'Arubanieuws.nu'),
  'Arubanieuws.nu': ('Buitenland', 'Arubanieuws.nu'),
  'Bonaire.nu': ('Buitenland', 'Bonaire.nu'),
  'bonaire.nu': ('Buitenland', 'Bonaire.nu'),
  'Bonairenieuws.nu': ('Buitenland', 'Bonaire.nu'),
  'Buitenland': ('Buitenland', 'Buitenland'),
  'Caribean Network': ('Buitenland', 'Caribisch Netwerk'),
  'Caribisch, NIEUWS': ('Buitenland', 'Caribisch Netwerk'),
  'Caribisch Nederland': ('Buitenland', 'Caribisch Netwerk'),
  'Caribisch netwerk': ('Buitenland', 'Caribisch Netwerk'),
  'Caribisch Netwerk': ('Buitenland', 'Caribisch Netwerk'),
  'Caribischnetwerk': ('Buitenland', 'Caribisch Netwerk'),
  'Caribischnetwerk ': ('Buitenland', 'Caribisch Netwerk'),
  'caribischnetwerk.ntr.nl': ('Buitenland', 'Caribisch Netwerk'),
  'Caribischnetwerk.ntr.nl': ('Buitenland', 'Caribisch Netwerk'),
  'Curacao.nu': ('Buitenland', 'Curacao.nu'),
  'Curacao.nu 27december 2019': ('Buitenland', 'Curacao.nu'),
  'Curacaonieuws.nu': ('Buitenland', 'Curacaonieuws.nu'),
  'Curaçaonieuws.nu': ('Buitenland', 'Curacaonieuws.nu'),
  'Daily Herald': ('Buitenland', 'Daily Herald'),
  'Daily herald': ('Buitenland', 'Daily Herald'),
  'daily herald': ('Buitenland', 'Daily Herald'),
  'DailyH': ('Buitenland', 'Daily Herald'),
  'DailyHerald': ('Buitenland', 'Daily Herald'),
  'Der Spiegel': ('Buitenland', 'Der Spiegel'),
  'Die Welt': ('Buitenland', 'Die Welt'),
  'Koningrijk.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'Koninkrijk.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'koninkrijk.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'Koninkrijkrelaties.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'Koninkrijksrelaties': ('Buitenland', 'Koninkrijksrelaties'),
  'Koninkrijksrelaties.nl': ('Buitenland', 'Koninkrijksrelaties'),
  'koninkrijksrelaties.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'Koninkrijksrelaties.nu': ('Buitenland', 'Koninkrijksrelaties'),
  'Metronieuws.be': ('Buitenland', 'Metronieuws.be'),
  'NTR Caribisch netwerk': ('Buitenland', 'Caribisch Netwerk'),
  'Reuters': ('Buitenland', 'Reuters'),
  'The Daily Herald': ('Buitenland', 'Daily Herald'),
  'thedailyherald.com': ('Buitenland', 'Daily Herald'),
  'Thedailyherald.com': ('Buitenland', 'Daily Herald'),
  'Today': ('Buitenland', 'Today'),
  'TV Visie.be': ('Buitenland', 'TV Visie.be'),
  'Cobouw': ('Cobouw', 'Cobouw'),
  'cobouw': ('Cobouw', 'Cobouw'),
  'Cobouw ': ('Cobouw', 'Cobouw'),
  'Cobouw 06:00': ('Cobouw', 'Cobouw'),
  'Cobouw 17-10- 2016': ('Cobouw', 'Cobouw'),
  'Cobouw 20 November': ('Cobouw', 'Cobouw'),
  'Cobouw Gisteren': ('Cobouw', 'Cobouw'),
  'Cobouw zaterdag': ('Cobouw', 'Cobouw'),
  'Cobouw.nl': ('Cobouw', 'Cobouw'),
  'Cobouw.nl ': ('Cobouw', 'Cobouw'),
  'Cobouw.nl  ': ('Cobouw', 'Cobouw'),
  'Cobouw.nl  10-10-2013 (p.': ('Cobouw', 'Cobouw'),
  'Cobouw.nl:': ('Cobouw', 'Cobouw'),
  'Cobouw.nl  01-06-2013 (p.': ('Cobouw', 'Cobouw'),
  'De Telegraaf': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf 12 juli 2019 vrijdag': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf 12 juli 2019 vrijdag, Gehele Oplage': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf 15 juli 2019 maandag, Gehele Oplage': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf 16 juli 2019 dinsdag, Gehele Oplage': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf 17 juli 2019 woensdag, Gehele Oplage': ('De Telegraaf', 'De Telegraaf'),
  'De Telegraaf/Amsterdam': ('De Telegraaf', 'De Telegraaf'),
  'Telegaaf.nl': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf - website': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf zaterdag': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf.': ('De Telegraaf', 'De Telegraaf'),
  'telegraaf.nl': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf.nl': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf.nl 1o oktober 2018': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf.nl vrijdag': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf/Rotterdam': ('De Telegraaf', 'De Telegraaf'),
  'Telegraaf/Utrecht': ('De Telegraaf', 'De Telegraaf'),
  'De Volkskrant': ('De Volkskrant', 'De Volkskrant'),
  'de Volkskrant 12 juli 2019 vrijdag': ('De Volkskrant', 'De Volkskrant'),
  'de Volkskrant 13 juli 2019 zaterdag': ('De Volkskrant', 'De Volkskrant'),
  'de Volkskrant 15 juli 2019 maandag': ('De Volkskrant', 'De Volkskrant'),
  'De Volkskrant.nl': ('De Volkskrant', 'De Volkskrant'),
  'vk.nl': ('De Volkskrant', 'De Volkskrant'),
  'VK.nl': ('De Volkskrant', 'De Volkskrant'),
  'Vk.nl ': ('De Volkskrant', 'De Volkskrant'),
  'VK.nl ': ('De Volkskrant', 'De Volkskrant'),
  'Volkskrant': ('De Volkskrant', 'De Volkskrant'),
  'volkskrant  ': ('De Volkskrant', 'De Volkskrant'),
  'Volkskrant Magazine': ('De Volkskrant', 'De Volkskrant'),
  'Volkskrant Politiek': ('De Volkskrant', 'De Volkskrant'),
  'volkskrant.nl': ('De Volkskrant', 'De Volkskrant'),
  'Volkskrant.nl': ('De Volkskrant', 'De Volkskrant'),
  'Volkskrant.nl ': ('De Volkskrant', 'De Volkskrant'),
  'de Volkskrant': ('De Volkskrant', 'De Volkskrant'),
  'FD': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'FD.nl': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'fd.nl': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'FD.nl 15 juli 2019 maandag 09:04 AM GMT': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Financeel Dagblad': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Financieel Dagblad': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Financieele Dagblad': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad 12 juli 2019 vrijdag': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad 15 juli 2019 maandag 12:00 AM GMT': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad 16 juli 2019 dinsdag 12:00 AM GMT': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad 17 juli 2019 woensdag 12:00 AM GMT': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Het Financieele Dagblad - website': ('Het Financieele Dagblad', 'Het Financieele Dagblad'),
  'Metro': ('Metro', 'Metro'),
  'Metro (NL)': ('Metro', 'Metro'),
  'Metro (NL) 15 juli 2019 maandag, Gehele Oplage': ('Metro', 'Metro'),
  'Metro.nl': ('Metro', 'Metro'),
  'Metronieuws.nl': ('Metro', 'Metro'),
  'Metro NL': ('Metro', 'Metro'),
  'Automatisering gids': ('Nieuwssites', 'Automatisering gids'),
  'Boerenbusiness.nl': ('Nieuwssites', 'Boerenbusiness.nl'),
  'Bredavandaag.nl': ('Nieuwssites', 'Bredavandaag.nl'),
  'Correspondent': ('Nieuwssites', 'De Correspondent'),
  'De Correspondent': ('Nieuwssites', 'De Correspondent'),
  'de Correspondent': ('Nieuwssites', 'De Correspondent'),
  'De Speld': ('Nieuwssites', 'De Speld'),
  'decorrespondent.nl': ('Nieuwssites', 'De Correspondent'),
  'Dichtbij.nl ': ('Nieuwssites', 'Dichtbij.nl '),
  'Dichtbij.nl   ': ('Nieuwssites', 'Dichtbij.nl '),
  'Follow the money': ('Nieuwssites', 'Follow the money'),
  'ftm.nl': ('Nieuwssites', 'Follow the money'),
  'Ftm.nl': ('Nieuwssites', 'Follow the money'),
  'Geen Stijl': ('Nieuwssites', 'Geen Stijl'),
  'Het Laatste Nieuws': ('Nieuwssites', 'Het Laatste Nieuws'),
  'Leidscadagblad.nl ': ('Nieuwssites', 'Leidscadagblad.nl '),
  'Linda Nieuws.nl': ('Nieuwssites', 'Linda Nieuws.nl'),
  'Mediawatch': ('Nieuwssites', 'Mediawatch'),
  'MEDIAWATCH ': ('Nieuwssites', 'Mediawatch'),
  'Nieuws.nl': ('Nieuwssites', 'Nieuws.nl'),
  'Nieuws.nl ': ('Nieuwssites', 'Nieuws.nl'),
  'Nieuws.nl  ': ('Nieuwssites', 'Nieuws.nl'),
  'Nieuwssites': ('Nieuwssites', 'Nieuwssites'),
  'Nuzakelijk.nl': ('Nieuwssites', 'Nuzakelijk.nl'),
  'nvvb.nl': ('Nieuwssites', 'nvvb.nl'),
  'Oneworld.nl': ('Nieuwssites', 'Oneworld.nl'),
  'Peil.nl': ('Nieuwssites', 'Peil.nl'),
  'Politiek': ('Nieuwssites', 'Politiek'),
  'Politiek.tpo.nl': ('Nieuwssites', 'ThePostOnline'),
  'Post Online': ('Nieuwssites', 'ThePostOnline'),
  'Rd.nl': ('Nieuwssites', 'Rd.nl'),
  'RePublic.nl': ('Nieuwssites', 'RePublic.nl'),
  'Sargasso.nl': ('Nieuwssites', 'Sargasso.nl'),
  'Security.nl': ('Nieuwssites', 'Security.nl'),
  'Sleutelstad.nl': ('Nieuwssites', 'Sleutelstad.nl'),
  'The Postonline': ('Nieuwssites', 'ThePostOnline'),
  'ThePostOnline': ('Nieuwssites', 'ThePostOnline'),
  'Thepostonline.nl': ('Nieuwssites', 'ThePostOnline'),
  'Thepostonline.nl ': ('Nieuwssites', 'ThePostOnline'),
  'Tweakers.net': ('Nieuwssites', 'Tweakers.nl'),
  'Tweakers.nl': ('Nieuwssites', 'Tweakers.nl'),
  'twitter': ('Nieuwssites', 'twitter'),
  'Versgeperst': ('Nieuwssites', 'Versgeperst'),
  'Versgeperst.com': ('Nieuwssites', 'Versgeperst'),
  'Villa Media': ('Nieuwssites', 'Villa Media'),
  'Volnieuws.nl': ('Nieuwssites', 'Volnieuws.nl'),
  'Webwereld ': ('Nieuwssites', 'Webwereld '),
  'Webwereld.nl': ('Nieuwssites', 'Webwereld '),
  'weespernieuws.nl': ('Nieuwssites', 'weespernieuws.nl'),
  'Zie.nl': ('Nieuwssites', 'Zie.nl'),
  'NOS TT': ('NOS ', 'NOS '),
  'Nos.nl  31-05-2013 (p.': ('NOS.nl', 'NOS.nl'),
  'NOSNieuws.nl': ('NOS.nl', 'NOS.nl'),
  ' NOS': ('NOS ', 'NOS '),
  ' NOS Journaal ': ('NOS ', 'NOS '),
  '18.00 uur': ('NOS ', 'NOS '),
  'Jeugdjournaal': ('NOS ', 'NOS '),
  'nos': ('NOS ', 'NOS '),
  'NOS': ('NOS ', 'NOS '),
  'NOS ': ('NOS ', 'NOS '),
  'NOS ': ('NOS ', 'NOS '),
  'NOS 1juli 2015': ('NOS ', 'NOS '),
  'NOS 20:00': ('NOS ', 'NOS '),
  'NOS Journaal': ('NOS ', 'NOS '),
  'Nos Journaal': ('NOS ', 'NOS '),
  'NOS Journal': ('NOS ', 'NOS '),
  'NOS nieuws': ('NOS ', 'NOS '),
  'NOS op 3': ('NOS ', 'NOS '),
  'NPO': ('NOS ', 'NOS '),
  'NPO 1': ('NOS ', 'NOS '),
  'NPO 1 Gesprek met de MP': ('NOS ', 'NOS '),
  'NPO 1 Het vragenuurtje': ('NOS ', 'NOS '),
  'NPO 3 Jeugdjornaal': ('NOS ', 'NOS '),
  'NPO1': ('NOS ', 'NOS '),
  'Vragenuurtje': ('NOS ', 'NOS '),
  'http://nos.nl/video/661869-eerste-drie-aardehuizen-klaar.html': ('NOS.nl', 'NOS.nl'),
  'nos.nl': ('NOS.nl', 'NOS.nl'),
  'NOS.nl': ('NOS.nl', 'NOS.nl'),
  'Nos.nl': ('NOS.nl', 'NOS.nl'),
  'Nos.nl ': ('NOS.nl', 'NOS.nl'),
  'Nos.nl  ': ('NOS.nl', 'NOS.nl'),
  'Nos.nl vrijdag': ('NOS.nl', 'NOS.nl'),
  'next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'Next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NEXT': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC - website': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC Handelsblad': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC Handelsblad (Adamse editie)': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC Next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC Next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC Weekend': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC zaterdag': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.NEXT': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.NEXT 12 juli 2019 vrijdag': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.NEXT 12 juli 2019 vrijdag, 1ste Editie': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.NEXT 15 juli 2019 maandag, 1ste Editie': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.NEXT 16 juli 2019 dinsdag, 1ste Editie': ('NRC Handelsblad', 'NRC Handelsblad'),
  'nrc.nl': ('NRC Handelsblad', 'NRC Handelsblad'),
  'Nrc.nl': ('NRC Handelsblad', 'NRC Handelsblad'),
  'nrcnext': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRCQ.nl': ('NRC Handelsblad', 'NRC Handelsblad'),
  'Tekst Tom-Jan Meeus Illustratie Ruben L. Oppenheimer': ('NRC Handelsblad', 'NRC Handelsblad'),
  'nrc': ('NRC Handelsblad', 'NRC Handelsblad'),
  'nrc next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC-next': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRC.nl': ('NRC Handelsblad', 'NRC Handelsblad'),
  'NRCnext': ('NRC Handelsblad', 'NRC Handelsblad'),
  'Nu.nl  01-06-2013 (p.': ('NU.nl', 'NU.nl'),
  'Nu.nl': ('NU.nl', 'NU.nl'),
  'nu.nl': ('NU.nl', 'NU.nl'),
  'NU.nl': ('NU.nl', 'NU.nl'),
  'Nu.nl ': ('NU.nl', 'NU.nl'),
  'nu.nl - website': ('NU.nl', 'NU.nl'),
  'Nu.nl  31-05-2013 (p.': ('NU.nl', 'NU.nl'),
  'Nu.cw': ('NU.nl', 'NU.nl'),
  'Aedes': ('Overig', 'Aedes'),
  'Aedes.nl': ('Overig', 'Aedes'),
  'ant': ('Overig', 'ant'),
  'Automatisering Gids': ('Overig', 'Automatisering Gids'),
  'Automatiseringsgids.nl': ('Overig', 'Automatisering Gids'),
  'BES Reporter': ('Overig', 'BES Reporter'),
  'Binnenland': ('Overig', 'Binnenland'),
  'Binnenlandredactie': ('Overig', 'Binnenlandredactie'),
  'Bits of Freedom': ('Overig', 'Bits of Freedom'),
  'bouwformatie.nl': ('Overig', 'bouwformatie.nl'),
  'Bouwinontwikkeling.nl': ('Overig', 'Bouwinontwikkeling.nl'),
  'CarNet': ('Overig', 'CarNet'),
  'Clean Totaal': ('Overig', 'Clean Totaal'),
  'Computable': ('Overig', 'Computable'),
  'Computable.nl': ('Overig', 'Computable'),
  'Computable.nl ': ('Overig', 'Computable'),
  'Computerworld': ('Overig', 'Computerworld'),
  'De Persdienst': ('Overig', 'De Persdienst'),
  'Dichtbij.nl': ('Overig', 'Dichtbij'),
  'Door: Joost De Vries': ('Overig', 'Overig'),
  'Eigenhuis.nl': ('Overig', 'Eigenhuis.nl'),
  'energeia.nl': ('Overig', 'energeia.nl'),
  'Forum': ('Overig', 'Forum'),
  'Katholieknieuwsblad.nl': ('Overig', 'Katholieknieuwsblad.nl'),
  'Locus (Propertynl)': ('Overig', 'Locus (Propertynl)'),
  'Maarten van Ast': ('Overig', 'Overig'),
  'Mediaplanet (FD)': ('Overig', 'Mediaplanet (FD)'),
  'MEdiawatch': ('Overig', 'Mediawatch'),
  'MHOOM': ('Overig', 'MHOOM'),
  'Nederlands Dagblad': ('Overig', 'Nederlands Dagblad'),
  'Nederlands Dagblad ': ('Overig', 'Nederlands Dagblad'),
  'ND': ('Overig', 'Nederlands Dagblad'),
  'ND.nl': ('Overig', 'Nederlands Dagblad'),
  'Nieuws of Nonsens': ('Overig', 'Nieuws of Nonsens'),
  'NOS Teletekst': ('Overig', 'Teletekst'),
  'NOSTT': ('Overig', 'Teletekst'),
  'Nutech': ('Overig', 'Nutech'),
  'Nutech.nl': ('Overig', 'Nutech'),
  'NVM.nl': ('Overig', 'NVM.nl'),
  'Opsporing Gezocht': ('Overig', 'Opsporing Gezocht'),
  'Overig': ('Overig', 'Overig'),
  'Persdienst': ('Overig', 'De Persdienst'),
  'Quotenet.nl': ('Overig', 'Quotenet.nl'),
  'Re.Public': ('Overig', 'Republic '),
  'redactie': ('Overig', 'Overig'),
  'Redormatorisch Dagblad': ('Overig', 'Reformatorisch Dagblad'),
  'Refdag.nl': ('Overig', 'Reformatorisch Dagblad'),
  'Reformatorisch Dagblad': ('Overig', 'Reformatorisch Dagblad'),
  'Reformatorisch dagblad': ('Overig', 'Reformatorisch Dagblad'),
  'Reformatorisch Dagblad ': ('Overig', 'Reformatorisch Dagblad'),
  'Reformatorisch Dagblad.nl': ('Overig', 'Reformatorisch Dagblad'),
  'Ref DB': ('Overig', 'Reformatorisch Dagblad'),
  'Republic': ('Overig', 'Republic '),
  'Rianne Heus': ('Overig', 'Overig'),
  'SIRIS.nl': ('Overig', 'SIRIS'),
  'SP.nl/wereld': ('Overig', 'SP'),
  'Spits': ('Overig', 'Spits'),
  'Spitsnieuws': ('Overig', 'Spits'),
  'Telecompaper': ('Overig', 'Telecompaper'),
  'Telecompaper.com': ('Overig', 'Telecompaper'),
  'Teletekst': ('Overig', 'Teletekst'),
  'tt.com': ('Overig', 'tt.com'),
  'unknown': ('Overig', 'Overig'),
  'unknown medium': ('Overig', 'Overig'),
  'Vergeperst': ('Overig', 'Vergeperst'),
  'Versgeperst.com ': ('Overig', 'Vergeperst'),
  'VNG': ('Overig', 'VNG'),
  'VNG Magazine': ('Overig', 'VNG'),
  'Webwereld': ('Overig', 'Webwereld'),
  'webwereld': ('Overig', 'Webwereld'),
  'zorgvisie.nl': ('Overig', 'zorgvisie.nl'),
  '01-06-2013 (p.': ('Overig', 'Overig'),
  'Argos': ('Radio', 'Argos'),
  'bnr': ('Radio', 'BNR '),
  'BNR ': ('Radio', 'BNR '),
  'BNR Bouwmeesters': ('Radio', 'BNR '),
  'BNR Hemmen': ('Radio', 'BNR '),
  'BNR Juridische Zaken': ('Radio', 'BNR '),
  'BNR Nieuwsradio': ('Radio', 'BNR '),
  'BNR Nieuwsradio vrjdag': ('Radio', 'BNR '),
  'BNR Spitsuur': ('Radio', 'BNR '),
  'bnr.nl': ('Radio', 'BNR '),
  'Een Vandaag Radio': ('Radio', 'Een Vandaag Radio'),
  'Kamerbreed': ('Radio', 'Kamerbreed'),
  'Langs de Lijn en Omstreken': ('Radio', 'NPO Radio 1'),
  'Met Het Oog Op Morgen': ('Radio', 'Met het oog op morgen'),
  'Met het oog op morgen': ('Radio', 'Met het oog op morgen'),
  'NPO Radio 1': ('Radio', 'NPO Radio 1'),
  'NPO Radio 2': ('Radio', 'NPO Radio 2'),
  'nporadio1.nl': ('Radio', 'NPO Radio 1'),
  'NPORadio1.nl': ('Radio', 'NPORadio1.nl'),
  'Opiniemakers': ('Radio', 'Opiniemakers'),
  'R1': ('Radio', 'NPO Radio 1'),
  'Radiio 1': ('Radio', 'NPO Radio 1'),
  'Radio': ('Radio', 'NPO Radio 1'),
  'Radio 1': ('Radio', 'NPO Radio 1'),
  'radio 1': ('Radio', 'NPO Radio 1'),
  'Radio 1 5 juli zaterdag 2014': ('Radio', 'Opiniemakers'),
  'Radio 1 Argos': ('Radio', 'Radio 1 Argos'),
  'Radio 1 De Taalstaat': ('Radio', 'NPO Radio 1'),
  'Radio 1 Focus': ('Radio', 'Radio 1 Focus'),
  'Radio 1 Haagse Lobby': ('Radio', 'Radio 1 Haagse Lobby'),
  'Radio 1 HMOOM': ('Radio', 'Radio 1 HMOOM'),
  'Radio 1 Journaal': ('Radio', 'Radio1 Journaal'),
  'Radio 1 Nieuws en Co': ('Radio', 'NPO Radio 1'),
  'radio 1 Opiniemakers': ('Radio', 'NPO Radio 1'),
  'Radio 1 Radar': ('Radio', 'Radio 1 Radar'),
  'Radio 2': ('Radio', 'Radio 2'),
  'Radio 4': ('Radio', 'Radio 4'),
  'Radio Doc': ('Radio', 'Doc'),
  'Radio Een Vandaag': ('Radio', 'Een Vandaag Radio'),
  'Radio I Kamerbreed': ('Radio', 'Kamerbreed'),
  'Radio1': ('Radio', 'NPO Radio 1'),
  'Radio1 Journaal': ('Radio', 'Radio1 Journaal'),
  'Radio1Journaal': ('Radio', 'Radio1 Journaal'),
  'Rambam': ('Radio', 'Rambam'),
  'Reporter Radio': ('Radio', 'Reporter Radio'),
  'Spijkers met koppen': ('Radio', 'Spijkers met koppen'),
  'Stand.nl': ('Radio', 'Stand.nl'),
  'Terzake': ('Radio', 'Terzake'),
  'Tros Kamerbreed': ('Radio', 'Kamerbreed'),
  'TROS Kamerbreed': ('Radio', 'NPO Radio 1'),
  '1Limburg.nl': ('Regionaal', '1Limburg'),
  'AD / Utrecht': ('Regionaal', 'AD/Utrechts Dagblad'),
  'AD Amersfoortse Courant': ('Regionaal', 'AD Amersfoortse Courant'),
  'AD/Amersfoortse Courant': ('Regionaal', 'AD Amersfoortse Courant'),
  'AD Groene Hart': ('Regionaal', 'AD Groene Hart'),
  'AD HC': ('Regionaal', 'AD/Haagsche Courant'),
  'AD Rotterdams Dagblad': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'AD-RD': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'AD/De Dordtenaar': ('Regionaal', 'AD/De Dordtenaar'),
  'AD/Groene Hart': ('Regionaal', 'AD/Groene Hart'),
  'AD Haagsche Courant': ('Regionaal', 'AD/Haagsche Courant'),
  'AD/Haagsche Courant': ('Regionaal', 'AD/Haagsche Courant'),
  'AD/Haagsche Courant 12 juli 2019 vrijdag': ('Regionaal', 'AD/Haagsche Courant'),
  'AD/Haagsche Courant 15 juli 2019 maandag': ('Regionaal', 'AD/Haagsche Courant'),
  'AD/HC ': ('Regionaal', 'AD/Haagsche Courant'),
  'AD/RD': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'AD/Rivierenland': ('Regionaal', 'AD/Rivierenland'),
  'AD/Rotterdams Dagblad': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'AD/Rotterdams Dagblad ': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'AD/Utrechts Dagblad': ('Regionaal', 'AD/Utrechts Dagblad'),
  'AD/Utrechts Nieuwsblad': ('Regionaal', 'AD/Utrechts Dagblad'),
  'AD Rotterdams': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'Rotterdams Dagblad': ('Regionaal', 'AD/Rotterdams Dagblad'),
  'Algemeen Dagblad Haagse editie': ('Regionaal', 'AD/Haagsche Courant'),
  'AlkmaarCentraal.nl': ('Regionaal', 'AlkmaarCentraal.nl'),
  'Almere Nieuws.nl': ('Regionaal', 'Almere Nieuws.nl'),
  'Almere Vandaag': ('Regionaal', 'Almere Vandaag'),
  'Almeredezeweek.nl': ('Regionaal', 'Almeredezeweek.nl'),
  'Almerevandaag': ('Regionaal', 'Almere Vandaag'),
  'Alphen.cc': ('Regionaal', 'Alphen.cc'),
  'Amersfoort Nu': ('Regionaal', 'Amersfoort Nu'),
  'at5': ('Regionaal', 'AT5'),
  'AT5': ('Regionaal', 'AT5'),
  'BD.nl': ('Regionaal', 'Brabants Dagblad'),
  'BN/De Stem': ('Regionaal', 'BN/De Stem'),
  'BN/De Stem ': ('Regionaal', 'BN/De Stem'),
  'BN/DeStem': ('Regionaal', 'BN/De Stem'),
  'BN/DeStem ': ('Regionaal', 'BN/De Stem'),
  'BN/DeStem.nl': ('Regionaal', 'BN/De Stem'),
  'bndestem.nl': ('Regionaal', 'BN/De Stem'),
  'Brabantsdagblad.nl': ('Regionaal', 'Brabants Dagblad'),
  'Brabants DAgblad': ('Regionaal', 'Brabants Dagblad'),
  'Brabants Dagblad': ('Regionaal', 'Brabants Dagblad'),
  'Brabants Dagblad.nl': ('Regionaal', 'Brabants Dagblad'),
  'Dagblad De Limburger': ('Regionaal', 'Dagblad De Limburger'),
  'Dagblad de Limburger': ('Regionaal', 'Dagblad De Limburger'),
  'Dagblad De Limburger ': ('Regionaal', 'Dagblad De Limburger'),
  'Dagblad Flevoland': ('Regionaal', 'Dagblad Flevoland'),
  'Dagblad Tubantia/Twentsche Courant': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'Dagblad van het Noorden': ('Regionaal', 'Dagblad van het Noorden'),
  'Dablad van het Noorden': ('Regionaal', 'Dagblad van het Noorden'),
  'De Gelderlander': ('Regionaal', 'De Gelderlander'),
  'De Gooi- en Eemlander': ('Regionaal', 'De Gooi- en Eemlander'),
  'De Limburger': ('Regionaal', 'Dagblad De Limburger'),
  'De Limburger - Limburgs Dagblad': ('Regionaal', 'Dagblad De Limburger'),
  'de Limburger.nl': ('Regionaal', 'Dagblad De Limburger'),
  'De Stentor': ('Regionaal', 'De Stentor'),
  'de stentor': ('Regionaal', 'De Stentor'),
  'De Stentor / Sallands Dagblad': ('Regionaal', 'De Stentor'),
  'De Stentor ': ('Regionaal', 'De Stentor'),
  'De Stentor  Dagblad Flevoland': ('Regionaal', 'De Stentor'),
  'De Stentor / Apeldoornse Courant': ('Regionaal', 'De Stentor'),
  'De Stentor / Dagblad Flevoland': ('Regionaal', 'De Stentor'),
  'De Stentor / Gelders Dagblad': ('Regionaal', 'De Stentor'),
  'De Stentor / Veluws Dagblad': ('Regionaal', 'De Stentor'),
  'De Stentor/ Deventer Dagblad': ('Regionaal', 'De Stentor'),
  'De Stentor/Veluws Dagblad': ('Regionaal', 'De Stentor'),
  'De Twentsche Courant Tubantia': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'De Twentsche Courant Tubantia ': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'Delimburger.nl': ('Regionaal', 'Dagblad De Limburger'),
  'Den Haag FM': ('Regionaal', 'Den Haag FM'),
  'Destentor.nl': ('Regionaal', 'De Stentor'),
  'Destentor.nl  ': ('Regionaal', 'De Stentor'),
  'Deventer Centraal': ('Regionaal', 'Deventer Centraal'),
  'DUIC': ('Regionaal', 'DUIC'),
  'DvhN': ('Regionaal', 'Dagblad van het Noorden'),
  'DvhN ': ('Regionaal', 'Dagblad van het Noorden'),
  'DvhN.nl': ('Regionaal', 'Dagblad van het Noorden'),
  'ED.nl': ('Regionaal', 'Eindhovens Dagblad'),
  'Eindhovens Dagblad': ('Regionaal', 'Eindhovens Dagblad'),
  'Eindhovens Dagblad.nl': ('Regionaal', 'Eindhovens Dagblad'),
  'Eindhovensdagblad.nl': ('Regionaal', 'Eindhovens Dagblad'),
  'Friesch Dagblad': ('Regionaal', 'Friesch Dagblad'),
  'Friesch Dagblad.nl': ('Regionaal', 'Friesch Dagblad'),
  'frieschdagblad.nl': ('Regionaal', 'Friesch Dagblad'),
  'Gelderlander': ('Regionaal', 'De Gelderlander'),
  'Gelderlander ': ('Regionaal', 'De Gelderlander'),
  'Gelderlander.nl': ('Regionaal', 'De Gelderlander'),
  'gelderlander.nl': ('Regionaal', 'De Gelderlander'),
  'omroepgelderland.nl': ('Regionaal', 'De Gelderlander'),
  'Gooi en Eemlander ': ('Regionaal', 'De Gooi- en Eemlander'),
  'Gooi- en Eemlander': ('Regionaal', 'De Gooi- en Eemlander'),
  'Gooi- en Eemlander.nl': ('Regionaal', 'De Gooi- en Eemlander'),
  'Groot Bergen op Zoom': ('Regionaal', 'Groot Bergen op Zoom'),
  'Groot Eindhoven': ('Regionaal', 'Groot Eindhoven'),
  'Haagsche Courant': ('Regionaal', 'AD/Haagsche Courant'),
  'Haarlems Dagblad': ('Regionaal', 'Haarlems Dagblad'),
  'Haarlems Dagblad.nl': ('Regionaal', 'Haarlems Dagblad'),
  'Het Parool': ('Regionaal', 'Het Parool'),
  'Het Parool.nl': ('Regionaal', 'Het Parool'),
  'IJmuider Courant': ('Regionaal', 'IJmuider Courant'),
  'IJmuider Courant.nl': ('Regionaal', 'IJmuider Courant'),
  'L1': ('Regionaal', 'L1'),
  'L1 TV': ('Regionaal', 'L1'),
  'L1.nl': ('Regionaal', 'L1'),
  'L1.nl 17september 2015': ('Regionaal', 'L1'),
  'LC.nl': ('Regionaal', 'Leeuwarder Courant'),
  'Leeuwarder Courant': ('Regionaal', 'Leeuwarder Courant'),
  'Leeuwarder Courant ': ('Regionaal', 'Leeuwarder Courant'),
  'Leeuwarder Courant.nl': ('Regionaal', 'Leeuwarder Courant'),
  'Leidsch Dagblad.nl': ('Regionaal', 'Leidsch Dagblad'),
  'Leidsch Dagblad': ('Regionaal', 'Leidsch Dagblad'),
  'Leidschdagblad.nl': ('Regionaal', 'Leidsch Dagblad'),
  'Leusderkrant.nl': ('Regionaal', 'Leusderkrant.nl'),
  'Limburg1': ('Regionaal', '1Limburg'),
  'Limburger.nl': ('Regionaal', 'Limburger.nl'),
  'Limburgs Dagblad': ('Regionaal', 'Dagblad De Limburger'),
  'Limburgsdagblad.nl': ('Regionaal', 'Dagblad De Limburger'),
  'NH Nieuws.nl': ('Regionaal', 'RTV NH'),
  'NHD.nl': ('Regionaal', 'Noordhollands Dagblad'),
  'Nieuwsblad de Kaap': ('Regionaal', ' Stichtse Courant'),
  'Noord-Hollands Dagblad ': ('Regionaal', 'Noordhollands Dagblad'),
  'Noordhollanddagblad.nl': ('Regionaal', 'Noordhollands Dagblad'),
  'Noordhollands Dagblad': ('Regionaal', 'Noordhollands Dagblad'),
  'Noordhollandsdagblad.nl': ('Regionaal', 'Noordhollands Dagblad'),
  'omroepbrabant.nl': ('Regionaal', 'Omroep Brabant'),
  'Omroep Brabant': ('Regionaal', 'Omroep Brabant'),
  'Omroep Flevoland': ('Regionaal', 'Omroep Flevoland'),
  'Omroepflevoland,nl': ('Regionaal', 'Omroep Flevoland'),
  'Omroep Friesland': ('Regionaal', 'Omroep Friesland'),
  'Omroep Gelderland': ('Regionaal', 'Omroep Gelderland'),
  'Omroep Gelderland ': ('Regionaal', 'Omroep Gelderland'),
  'Omroep Gelderland  10-10-2013 (p.': ('Regionaal', 'Omroep Gelderland'),
  'Omroep Radio Brabant': ('Regionaal', 'Omroep Brabant'),
  'Omroep Venlo': ('Regionaal', 'Omroep Venlo'),
  'Omroep West': ('Regionaal', 'Omroep West'),
  'Omroep West ': ('Regionaal', 'Omroep West'),
  'Omroep Zeeland': ('Regionaal', 'Omroep Zeeland'),
  'Omroepbrabant.nl ': ('Regionaal', 'Omroep Brabant'),
  'Omroepflevoland': ('Regionaal', 'Omroep Flevoland'),
  'Omroepflevoland.nl': ('Regionaal', 'Omroep Flevoland'),
  'OmroepFriesland.nl': ('Regionaal', 'Omroep Friesland'),
  'Omroepgelderland.nl': ('Regionaal', 'Omroep Gelderland'),
  'Omroepwest.nl': ('Regionaal', 'Omroep West'),
  'Omroepzeeland.nl': ('Regionaal', 'Omroep Zeeland'),
  'oogtv.nl': ('Regionaal', 'OogTV'),
  'Parool': ('Regionaal', 'Het Parool'),
  'Parool.nl': ('Regionaal', 'Het Parool'),
  'parool': ('Regionaal', 'Het Parool'),
  'Parool website': ('Regionaal', 'Het Parool'),
  'parool.nl': ('Regionaal', 'Het Parool'),
  'PCM': ('Regionaal', 'PCM'),
  'Provinciale Zeeuwse Courant': ('Regionaal', 'PZC'),
  'PZC': ('Regionaal', 'PZC'),
  'PZC.nl': ('Regionaal', 'PZC'),
  'Pzc.nl ': ('Regionaal', 'PZC'),
  'Radio Drenthe': ('Regionaal', 'RTV Drenthe'),
  'rtv drenthe': ('Regionaal', 'RTV Drenthe'),
  'Radio Flevoland': ('Regionaal', 'Radio Flevoland'),
  'Radio M Utrecht': ('Regionaal', 'Radio M Utrecht'),
  'Radio NH': ('Regionaal', 'RTV NH'),
  'Radio Noord': ('Regionaal', 'RTV Noord'),
  'Radio Oost': ('Regionaal', 'RTV Oost'),
  'Radio Rijnmond': ('Regionaal', 'RTV Rijnmond'),
  'Radio Utrecht': ('Regionaal', 'RTV Utrecht'),
  'Radio West': ('Regionaal', 'RTV West'),
  'Regionaal': ('Regionaal', 'Regionaal'),
  'Rijnmond nieuws': ('Regionaal', 'RTV Rijnmond'),
  'Rijnmond.nl': ('Regionaal', 'RTV Rijnmond'),
  'RTV': ('Regionaal', 'RTV'),
  'Rtvdrenthe': ('Regionaal', 'RTV Drenthe'),
  'RTV Drenthe': ('Regionaal', 'RTV Drenthe'),
  'RTV Drenthe.nl': ('Regionaal', 'RTV Drenthe'),
  'RTV Maastricht': ('Regionaal', 'RTV Maastricht'),
  'RTV N-H': ('Regionaal', 'RTV NH'),
  'RTV NH': ('Regionaal', 'RTV NH'),
  'RTV Noord': ('Regionaal', 'RTV Noord'),
  'rtv Noord': ('Regionaal', 'RTV Noord'),
  'Rtvnoord.nl': ('Regionaal', 'RTV Noord'),
  'RTV Noord-Holland': ('Regionaal', 'RTV NH'),
  'Rtv Noord-Holland': ('Regionaal', 'RTV NH'),
  'Rtvnoordholland.nl': ('Regionaal', 'RTV NH'),
  'RTV Oost': ('Regionaal', 'RTV Oost'),
  'RTV Oost ': ('Regionaal', 'RTV Oost'),
  'RTV Oost.nl': ('Regionaal', 'RTV Oost'),
  'RTV Rijnmond': ('Regionaal', 'RTV Rijnmond'),
  'RTV-rijnmond': ('Regionaal', 'RTV Rijnmond'),
  'RTV Utrecht': ('Regionaal', 'RTV Utrecht'),
  'RTV Utrecht ': ('Regionaal', 'RTV Utrecht'),
  'RTV Utrecht.nl': ('Regionaal', 'RTV Utrecht'),
  'RTV West': ('Regionaal', 'RTV West'),
  'RTVD': ('Regionaal', 'RTV Drenthe'),
  'Rtvdrenthe.nl': ('Regionaal', 'RTV Drenthe'),
  'rtvnoord': ('Regionaal', 'RTV Noord'),
  'rtvnoord.nl': ('Regionaal', 'RTV Noord'),
  'Rtvoost.nl': ('Regionaal', 'RTV Oost'),
  'Rtvrijnmond.nl': ('Regionaal', 'Regionaal'),
  'Rtvutrecht.nl': ('Regionaal', 'RTV Utrecht'),
  'RTVUttrecht.nl': ('Regionaal', 'RTV Utrecht'),
  'Stentor': ('Regionaal', 'De Stentor'),
  'Stentor.nl': ('Regionaal', 'De Stentor'),
  'Tubantia': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'Tubantia.nl': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'tvenschedefm.nl': ('Regionaal', 'tvenschedefm.nl'),
  'TW West': ('Regionaal', 'RTV West'),
  'Twentsche Courant Tubantia': ('Regionaal', 'Dagblad Tubantia/Twentsche Courant'),
  'Veenendaalsekrant.nl': ('Regionaal', 'Veenendaalsekrant.nl'),
  'Vlaardingen.nl': ('Regionaal', 'Vlaardingen.nl'),
  'Weespernieuws.nl': ('Regionaal', 'Weespernieuws.nl'),
  'Redactie RTL Nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL 4': ('RTL nieuws', 'RTL nieuws'),
  'rtl 4 5 Uur Live': ('RTL nieuws', 'RTL nieuws'),
  'RTL 4 Late nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL 4 Nieuws': ('RTL nieuws', 'RTL nieuws'),
  'rtl 4 nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL 7': ('RTL nieuws', 'RTL 7'),
  'RTL nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL Nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL Nieuws zaterdag': ('RTL nieuws', 'RTL nieuws'),
  'RTL Z': ('RTL nieuws', 'RTL Z'),
  'RTLZ.nl': ('RTL nieuws', 'RTL Z'),
  'RTL4': ('RTL nieuws', 'RTL nieuws'),
  'RTL4 nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL4 Nieuws': ('RTL nieuws', 'RTL nieuws'),
  'RTL7': ('RTL nieuws', 'RTL 7'),
  'RTLnieuws': ('RTL nieuws', 'RTL nieuws'),
  'Rtlnieuws.nl  01-06-2013 (p.': ('RTL.nl', 'RTL.nl'),
  'RTL Nieruws.nl': ('RTL.nl', 'RTL.nl'),
  'RTL nieuws.nl': ('RTL.nl', 'RTL.nl'),
  'RTL nieuws.nl': ('RTL.nl', 'RTL.nl'),
  'RTL Nieuws.nl': ('RTL.nl', 'RTL.nl'),
  'rtl.nl': ('RTL.nl', 'RTL.nl'),
  'RTL.nl': ('RTL.nl', 'RTL.nl'),
  'RTLnieuws.nl': ('RTL.nl', 'RTL.nl'),
  'Rtlnieuws.nl': ('RTL.nl', 'RTL.nl'),
  'rtlnieuws.nl': ('RTL.nl', 'RTL.nl'),
  'Rtlnieuws.nl ': ('rtl.nl', 'RTL.nl'),
  'Rtlnieuws.nl  ': ('rtl.nl', 'RTL.nl'),
  'Rtlnieuws.nl 31 januari': ('rtl.nl', 'RTL.nl'),
  'Rtlnieuws.nl vrijdag': ('RTL.nl', 'RTL.nl'),
  'Rtlnieuws.nl vrijdag 2 augustus 2013': ('rtl.nl', 'RTL.nl'),
  'webmaster-rtlnieuws@rtl.nl (Redactie RTL Nieuws)': ('rtl.nl', 'RTL.nl'),
  'Elsevier': ('Tijdschriften', 'Elsevier'),
  'Elsevier Weekblad': ('Tijdschriften', 'Elsevier'),
  'Elsevier.nl': ('Tijdschriften', 'Elsevier'),
  'Elsevier.nl ': ('Tijdschriften', 'Elsevier'),
  'Elsevierweekblad.nl': ('Tijdschriften', 'Elsevier'),
  'Groene Amsterdammer': ('Tijdschriften', 'Groene Amsterdammer'),
  'HP De Tijd': ('Tijdschriften', 'HP/De Tijd'),
  'HP/De Tijd': ('Tijdschriften', 'HP/De Tijd'),
  'hpdetijd.nl': ('Tijdschriften', 'HP/De Tijd'),
  'Katholiek Nieuwsblad': ('Tijdschriften', 'Katholiek Nieuwsblad'),`
  'Opiniebladen': ('Tijdschriften', 'Opiniebladen'),
  'Opiniebladenoverzicht week 37': ('Tijdschriften', 'Opiniebladen'),
  'Opiniebladenoverzicht week 38': ('Tijdschriften', 'Opiniebladen'),
  'Opiniebladenoverzicht week 39': ('Tijdschriften', 'Opiniebladen'),
  'Tijdschriften': ('Tijdschriften', 'Tijdschriften'),
  'Trouw': ('Trouw', 'Trouw'),
  'Trouw 15 juli 2019 maandag': ('Trouw', 'Trouw'),
  'Trouw 16 juli 2019 dinsdag': ('Trouw', 'Trouw'),
  'Trouw.NL': ('Trouw', 'Trouw'),
  'Trouw - website': ('Trouw', 'Trouw'),
}
