# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = '_initial_data'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='amcat')

class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0001_initial_amcat_3_5'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
