# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0001_initial_amcat_3_5'),
    ]

    operations = [
        # Empty, has been moved to 0007_initial_data, due to schema changes
    ]
