# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0004_auto_20170104_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RunSQL('DELETE FROM roles WHERE projectlevel=FALSE;'),
    ]
