# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0005_auto_20170104_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='role',
            name='projectlevel',
        ),
    ]
