# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 20:19
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', "_initial_data", app_label='amcat')

class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0006_auto_20170104_2016'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
