# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0003_default_elasticsearch_similarity'),
        ('amcat', '0007_initial_data'),
    ]

    operations = [
    ]
