# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 13:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUploadPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField()),
                ('presets', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_plugins', to='amcat.Project')),
            ],
            options={
                'db_table': 'projects_plugins',
            },
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='plugin_type',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.DeleteModel(
            name='PluginType',
        ),
        migrations.AlterUniqueTogether(
            name='projectplugin',
            unique_together=set([('name', 'project')]),
        ),
    ]
