# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-16 17:49
from __future__ import unicode_literals

import amcat.tools.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0008_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='plugin_type',
        ),
        migrations.AddField(
            model_name='project',
            name='upload_plugins',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[amcat.tools.validators.DictValidator(str, bool)]),
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.DeleteModel(
            name='PluginType',
        ),
    ]
