# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-27 16:34
from __future__ import unicode_literals

import amcat.models.article
import amcat.models.uploadedfile
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amcat', '0009_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(db_column='upload_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/amcat_upload'), upload_to=amcat.models.uploadedfile._get_upload_dir)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcat.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploadedfiles',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='properties',
            field=amcat.models.article.PropertyField(default='{}'),
        ),
    ]
