# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-26 17:28
from __future__ import unicode_literals

import amcat.models.project
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0010_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=('medium',), validators=[amcat.models.project.strlist_validator]),
        ),
    ]
