# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:49
from __future__ import unicode_literals

from django.db import migrations
from amcat.tools import amcates


def check_index(apps, schema_editor):
    amcates.ES().check_index()


class Migration(migrations.Migration):
    dependencies = [
        ('amcat', '0011_initial_data'),
    ]

    operations = [
        migrations.RunPython(check_index),
    ]
