# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-08 15:58
from __future__ import unicode_literals

import amcat.tools.hashing
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0012_merge_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=amcat.tools.hashing.HashField(db_index=True, max_length=28, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_hash',
            field=amcat.tools.hashing.HashField(blank=True, db_index=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='projectarticleset',
            name='articleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcat.ArticleSet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
