# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcat', '0013_auto_20190208_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingjob',
            options={'ordering': ('project_id', '-id')},
        ),
        migrations.AddField(
            model_name='codingjob',
            name='linked_projects',
            field=models.ManyToManyField(related_name='linked_codingjobs', to='amcat.Project'),
        ),
    ]
